
import 'react-multi-carousel/lib/styles.css';
import { FaHeadset, FaClock, FaMapMarkerAlt, FaMailBulk, FaFax } from 'react-icons/fa';
import colorSharp from "../assets/img/color-sharp.png"
import { Col, Row, Dropdown } from "react-bootstrap";

export const TermsInformation = () => {
    const responsive = {
        superLargeDesktop: {
            // the naming can be any, depends on you.
            breakpoint: { max: 4000, min: 3000 },
            items: 5
        },
        desktop: {
            breakpoint: { max: 3000, min: 1024 },
            items: 3
        },
        tablet: {
            breakpoint: { max: 1024, min: 464 },
            items: 2
        },
        mobile: {
            breakpoint: { max: 464, min: 0 },
            items: 1
        }
    };

    return (
        <section className="skill" id="skills">
            <div className="containerSkills">
                <div className="row">
                    <div className="col-12">
                        <div className="skill-faq wow zoomIn">
                            <h4>Terms & Conditons</h4>
                            <p>
                            <b>THIS IS AN IMPORTANT LEGAL DOCUMENT THAT GOVERNS THE TERMS AND CONDITIONS OF YOUR CONTRACT WITH Vertex-Solutions, INC. (“Vertex-Solutions”).  THESE TERMS AND CONDITIONS ARE A LEGAL AGREEMENT BETWEEN THE CUSTOMER AND Vertex-Solutions AND BY UTILIZING THE SERVICES OF Vertex-Solutions YOU AGREE TO BE BOUND ALL OF THE TERMS AND CONDITIONS SET FORTH BELOW. PLEASE READ THIS DOCUMENT CAREFULLY.</b> 
                            <br/>
                            <br/>
                            <b>1) Freight Brokerage:</b> Vertex-Solutions is a non-asset based, transportation freight broker registered with the Federal Motor Carrier Safety Administration (“FMCSA”), also known as a “Freight Logistics Company” or a “Freight Broker.” At no time does Vertex-Solutions hold, handle, store, take possession of, or transport freight. Customer acknowledges that Vertex-Solutions is a Freight Broker and NOT a “freight carrier”.
                            <br/>
                            <br/>
                            <b>2) Freight Carrier:</b> A carrier is a duly licensed and registered company that provides all or part of the actual transportation of Customer’s Shipment (“Carrier”). Such freight Carrier or Carriers that are engaged to transport the Shipment will be subject to all state and federal laws and regulations applicable to the transportation of the Shipment and, therefore, will be exclusively liable for the Shipment. Customer understands and agrees that the Carrier that takes possession of the freight and actually transports the Shipment  will be exclusively responsible for the transportation and delivery of the Shipment. Vertex-Solutions is not a Carrier.
                            <br/>
                            <br/>
                            <b>3) Customer Obligations:</b> Customer is responsible for providing accurate weights, sizes, dimensions, and descriptions of the Shipment including the freight class and National Motor Freight Classification (“NMFC”) code and failure to do so may result in additional charges. Customer understands that all freight rates are quoted for a business to business delivery and from dock to dock. Residential services are available and are charged as an accessorial service. If residential pickup and/or delivery are requested by Customer, Customer warrants the locations will be accessible to carrier equipment. Customer agrees to provide the means to load and unload the Shipment unless these services have been arranged for as an accessorial service. Customer agrees to ensure the Shipment is properly prepared for transport by the Carrier (with NMFC-compliant packaging and a proper address), and to ensure that any flatbed cargo is properly secured and tarped by the Carrier, unless these services have been arranged for by Customer with Vertex-Solutions as an accessorial service. Customer also agrees to ensure that the Carrier has obtained any necessary permits for oversize or overweight shipments, unless permitting services have been arranged for by Customer with Vertex-Solutions as an accessorial service. Customer AGREES TO PAY FOR ALL SERVICES AS ACTUALLY PROVIDED by Vertex-Solutions and the Carrier.
                            <br/>
                            <br/>
                            <b>4) Bill of Lading (“BOL”):</b> Customer is to provide the BOL to the Carrier. Vertex-Solutions shall have no obligation to make any payments, process or assist with any Claims, or honor any rate quotes if: (i) there has been unauthorized alteration or use of the BOL for the Shipment, or (ii) Customer releases the Freight for transport to a carrier other than the Carrier designated on the BOL, or (iii) Customer uses any BOL not authorized or issued by Vertex-Solutions. UNDER NO CIRCUMSTANCES SHALL Vertex-Solutions BE SHOWN ON THE BOL AS THE “CARRIER”. Accordingly, Customer agrees to hold such Carrier exclusively liable for loss or damages.
                            <br/>
                            <br/>
                                <b>(a) On Less-than-Truckload (“LTL”) Shipments:</b> Customer is required to use the Vertex-Solutions system generated BOL, which is issued by Vertex-Solutions as agent of the Customer. Customer agrees to sign that BOL prior to pickup. Customer must then provide, or cause its cosigner to provide, two (2) copies of the signed BOL to the Carrier at the point of pick-up. Customer, or an agent of Customer, shall consign the shipment directly to the actual transporting Carrier.
                                <br/>
                                <br/>
                                <b>(b) On Truckload (“TL”) Shipments:</b> A BOL is required, which Customer will print from Vertex-Solutions’s customer portal. If not issued by the Carrier, it may be issued by Vertex-Solutions as agent for Customer or by Customer itself. In all other respects, the provisions of paragraph 4(a) above shall apply to BOLs for LTL and TL shipments alike.
                            <br/>
                            <br/>
                            <b>5) Necessary Documentation:</b> If Customer does not complete all the documents required for carriage, or if the documents which it submits are not appropriate for the Services, Customer hereby instructs Vertex-Solutions, where permitted by law, to complete, correct or replace the documents for it at the expense of Customer. However, Vertex-Solutions is not obligated to do so. If a substitute form of BOL is needed to complete delivery of this shipment and Vertex-Solutions completes that document, the terms of the substitute BOL will govern. Vertex-Solutions is not liable to Customer or to any other person for any actions taken on behalf of Customer under this provision.
                            <br/>
                            <br/>
                            <b>6) BOL and Shipment Terms:</b> Any BOL generated under these Terms and Conditions is NON-NEGOTIABLE, has been prepared by the enrolled Customer itself, or by the Carrier or Vertex-Solutions on behalf of Customer, and shall be deemed, conclusively, to have been prepared by Customer. The General Rules Tariffs issued by the Carrier actually providing the transportation of the Shipment will in every instance take precedence over any BOL terms and over Vertex-Solutions’s Terms and Conditions stated herein, except that any attempt to designate Vertex-Solutions as a “Carrier” shall be void, and provided that the following shall be allowed only under such circumstances as may be specified in Vertex-Solutions’s agreement with Carrier: (a) direct billing of rates and charges by Carrier to Customer, (b) recourse by Carrier against any other party to the Shipment for payment of such rates and charges, and (c) exercise by Carrier of any statutory or common-law lien it otherwise might have upon Customer’s freight. In the case of conflict between these Terms and Conditions and those set forth by the Carrier’s General Rules Tariff, the Carrier’s General Rules Tariff shall control with exception and provisos just stated. If a matter is not covered by such General Rules Tariff, however, these Terms and Conditions shall control. Any applicable provisions of the Carrier’s General Rules Tariff and Vertex-Solutions’s Terms and Conditions including, but not limited to, all liability limitations shall apply not only to the selected Carrier but to its agents and subcontracted carriers.
                            <br/>
                            <br/>
                            <b>7) Customer’s Warranties:</b> Customer acknowledges its responsibility to comply with, and warrants its compliance with all applicable state and federal laws, rules, and regulations including, but not limited to, customs laws, import and export laws, economic sanctions (if recognized by the U.S. Government) and governmental regulation of any country to, from, through or over which the Shipment may be carried. Customer agrees to furnish such information and complete and attach to its Bill of Lading such documents as are necessary to comply with such laws, rules and regulations. Vertex-Solutions assumes no liability to Customer or to any other person for any loss or expense due to the failure of Customer to comply with this provision. Any individual or entity acting on behalf of Customer in scheduling shipments hereunder warrants that it has the right to act on behalf of Customer and the right to legally bind Customer.
                            <br/>
                            <br/>
                            <b>8) Vertex-Solutions may cancel this Agreement and refuse to undertake any service on behalf of Customer if any of the following occur: BOL is not signed by Customer, BOL attempts to designate Vertex-Solutions as the “Carrier,” unauthorized alteration or unauthorized use of the BOL, shipments tendered to any carrier other than that designated by Vertex-Solutions, and LTL shipments tendered with any BOL not issued by Vertex-Solutions.</b>
                            <b>9) Calculation of Rates and Charges:</b> Shipments are rated according to applicable pricing provisions offered by the Carrier, based on shipment information provided by Customer and approved by Customer. Rate calculation includes the type of item(s) being shipped (class), weight, size, volume, type of packing, number of items and commercial or residential pick-up or delivery, type of service requested and transit time. Shipping charges may include discounts from published carrier rates and are conditional based on payment within the Carrier’s payment terms. Pricing information in paragraphs. (10) and (11) below is based on terms typically available under Vertex-Solutions’s agreements with Carriers frequently selected by Vertex-Solutions’s customers. If such pricing terms are unacceptable to Customer, please notify Vertex-Solutions before tendering a shipment, specify desired terms, and Vertex-Solutions will make commercially reasonable efforts to find a Carrier meeting such terms. All amounts due for services purchased from Vertex-Solutions are due and payable at P.O. Box 15305, Santa Ana, CA 92735 within fifteen (15) days of invoice date without deduction or setoff. Vertex-Solutions specifically reserves the right to amend or adjust charges and to re-invoice the Customer if: (i) the original quoted amount was based upon incorrect information provided by the Customer; or (ii) additional services by the carrier were reasonably required; or (iii) the Customer authorized the Carrier to perform pick up, transportation, delivery, or other related functions other than contemplated by the BOL. Any dispute by customer of any invoice shall be made in writing, specifically indicating the nature of the dispute and made within thirty (30) days from the date of the invoice. If Vertex-Solutions does not receive timely written notice of the dispute, the charges will be conclusively presumed to be valid.
                            <br/>
                            <br/>
                            <b>10) LTL Service:</b> Rates for LTL Shipments are based on origin and destination zip codes, distance, commodity freight class per NMFC, net shipping weight (including all packing materials, crating and/or pallets) as a cost per pound, dimensions, nature of the freight, and volume of space required for transit as cost per cubic foot and/or length of truck.
                            <br/>
                            <br/>
                            <b>11) TL Service:</b> Rates for TL Shipments are based on Dock Door Pick-up/Dock Door Delivery and Shipper Load/Consignee Unload and are state to state and mileage based. Full truckload Shipments include two (2) hours of detention time at pick-up and delivery. Additional charges may apply under the selected Carrier’s pricing provisions, including but not limited to Tractor Detention, Trailer Detention, and Driver Assistance. Additional detention time typically will be charged by Carriers at $75 per hour, up to $600 per day. A cancellation charge typically will be assessed for all TL shipments cancelled less than four hours prior to the scheduled day and time of pick-up at the rate of $350.00 or 20%, whichever is greater. Expedited rates are based on actual or dimensional weight. If an expedited Shipment contains oversize freight, additional charges and transit days may apply. Blanket Wrap/High Value Goods rates are determined by state to state/mileage, weight (actual or density) and commodity/product type. Flat-bed rates are based on equipment type, state to state/mileage and weight. If a flat-bed shipment contains oversize freight, as determined by the state or states it will transport through, additional charges and transit days may apply.
                            <br/>
                            <br/>
                            <b>12) Guaranteed Transit Time Services:</b> Unless Guaranteed Service is specifically listed as a chargeable accessorial service, delivery times are estimates only. When Guaranteed Service is included as an accessorial service, it is inclusive of transit times only as noted by the Carrier selected. Guaranteed
                            Service transit times do not include holiday and/or no-service days as defined by the individual Carrier. This service is not a guarantee for a particular pick-up time. Pick-up Day is not included in the qualification and calculation of transit time. Delays caused by an Act of God, war, weather or delays due to State or Federal intervention negate the Guaranteed Transit Time service. Carrier liability for Guaranteed Transit Time shall, at no time, exceed the additional accessorial charge as noted on the invoice. In no case shall Customer hold the Carrier or Vertex-Solutions liable for losses, lost profits, lost opportunity, economic damages, expense, or special, consequential or incidental damages Customer may have experienced as a consequence of transit times greater than expected. In the event of Carrier’s failure to comply with the Guaranteed Service requested, Customer is permitted 10 business days from the date of invoice to file a claim request in writing with the Carrier in care of Vertex-Solutions. If Vertex-Solutions does not receive a claim request or receives the request after the allowable 10 business days, the service provided by the Carrier will be deemed to have met all Guaranteed Service standards and the claim request will automatically be considered invalid and denied. In the event a Carrier fails to provide the Guaranteed Transit Time service as arranged, Vertex-Solutions will credit the account of said Customer within 48 hours after Carrier has acknowledged liability. In no event shall Vertex-Solutions be liable for failure to meet the Guarantee, nor will any account be credited if Customer does not use Vertex-Solutions’s Bill of Lading.
                            <br/>
                            <br/>
                            <b>13) Because Vertex-Solutions is not a common carrier or a carrier of any kind, it reserves the right, in its sole discretion, to refuse any shipment at any time.</b>
                            <br/>
                            <br/>
                            <b>14) Delay of Shipment:</b> Neither Vertex-Solutions nor the selected Carrier shall be held liable for delays in delivery caused by accidents, governmental intervention, weather conditions, other acts of God, other causes referenced in the first sentence of paragraph 20 below, or any other circumstances that are beyond the control of Vertex-Solutions and/or the Carrier.
                            <br/>
                            <br/>
                            <b>15) reparation of Shipment: </b> Unless otherwise stated in a special agreement accepted in writing by both Parties, Customer is responsible for proper preparation, packing, load securement and addressing of the Shipment. Unless otherwise stated, Customer is responsible for providing the means to load and unload the Shipment.
                            <br/>
                            <br/>
                            <b>16) Claims and Limitations of Liability:</b> Vertex-Solutions is a Broker and shall not, under any circumstances, be liable to Customer for loss or damage to Customer’s goods.  Liability, if any, for such losses and damages to Customer shall be borne by the Carrier.  Vertex-Solutions does not insure or indemnify Customer against losses, damages, delays or other liability resulting from or incurred in connection with Shipment. In the event of a claim, Customer shall look solely to the Carrier and/or Customer’s own insurance in the event of a claim for damage or loss. If Customer is not the consignee, it agrees to cause the consignee to inspect the shipment at the time of delivery, and to document any damage on the delivery receipt prior to signing. Because the transportation of Customer’s freight is performed exclusively by the Carrier and not by Vertex-Solutions, the Customer agrees to hold Vertex-Solutions harmless for services (i.e. transportation of freight) performed by the Carrier. Customer agrees to pay Vertex-Solutions as per this Agreement regardless of any disputes that may or may not occur with the Carrier. Customer further understands and agrees that it will be subject to, and bound by, the Carrier’s specific limitations as to claims, losses and/or damages, and that it will not be able to recover any damages or losses in excess of such limitations.
                            <br/>
                            <br/>
                            <b>17) Third Party Coverage:</b> Although Vertex-Solutions is not an insurance company or insurance agent, it will endeavour to assist Customer, on Customer’s request, in obtaining third-party coverage through insurers with which Vertex-Solutions maintains commercial relationships. Should Customer purchase such third-party coverage through the assistance of Vertex-Solutions and subsequently decide to cancel the Shipment after the coverage has been purchased, the fees for third-party coverage are non-refundable and will not be credited to Customer’s account.
                            <br/>
                            <br/>
                            <b>18) Claims Assistance:</b> Although Vertex-Solutions is not a carrier and does not assume liability for cargo loss or damage in connection with Shipments it arranges, it will endeavour to assist Customer, on Customer’s request, with cargo loss and damage claims as Customer’s agent. If Customer desires such assistance, it must file a cargo claim in writing with Vertex-Solutions within 48 hours of delivery. Vertex-Solutions will assist Customer in the submission of Customer’s claim to the Carrier, but is in no event responsible for payment of such claims and makes no representation, warranty or guaranty as to the outcome of such claims or the availability of insurance coverage from which the Carrier may pay such claims. The filing of a claim does not relieve Customer of its responsibility for payment of freight charges. Customer’s account must be paid in full prior to Vertex-Solutions providing assistance to Customer in processing a claim against the Carrier for loss or damage.
                            <br/>
                            <br/>
                            <b>19) Exclusions of Liability:</b> In no event shall Vertex-Solutions be held liable for any loss, damage, misdelivery or non-delivery caused by: (i) the act, default or omission of a Carrier, the Customer or any other party who claims interest in the shipment; or (ii) the nature of the shipment or any defect therein; or (iii) a violation by the Customer of any provision of these Terms and Conditions, the BOL, the Carrier’s tariff, including, improper or insufficient packing, securing, marking or addressing; or (iv) failure to observe any of the rules relating to shipments not acceptable for transportation or shipments acceptable only under certain conditions; or (v) acts of God, perils of the air or sea, public enemies, public authorities, acts or omissions of customs or quarantine officials, war, terrorism, riots, strikes, labor disputes, shortages, weather conditions or mechanical delay or failure of vehicles, aircraft or other equipment; or (vi) the acts or omissions of any person other than employees of Vertex-Solutions. Customer acknowledges that in order to provide competitive rates for the services provided pursuant to these Terms and Conditions, the Parties have agreed as a material term of these Terms and Conditions that the risk of loss or damage incurred as a result of any Vertex-Solutions alleged liability shall be limited to the fees that Vertex-Solutions has earned with respect to the Shipment.  Vertex-Solutions’s liability, if any, for breach of warranty or covenant in Vertex-Solutions’s Terms and Conditions shall be limited to the total compensation paid by Customer for services provided by Vertex-Solutions.  The Carrier’s cargo liability for any one shipment shall not exceed $100,000 unless specifically stated otherwise.  Additional cargo insurance to cover the entire value of the shipment can be procured prior to the shipment pickup, upon timely advance request by Customer and at an additional expense to Customer.  Vertex-Solutions is not liable for losses, mis-delivery or non-delivery caused by violation(s) by Customer of any of the Terms and Conditions (as applicable), other applicable provisions in the Bill of Lading, or the requirements of a selected Carrier’s General Rules Tariff. In order to prevent mis-delivery through tender of freight to imposters purporting to act for a selected Carrier, it is the responsibility of Customer to see that the identity of the pickup driver and the markings on his/her equipment are checked at the point of pickup and that such is consistent with the Carrier identified on the BOL issued by Vertex-Solutions or generated through Vertex-Solutions’s system.
                            <br/>
                            <br/>
                            <b>20) Disclaimer of Warranties:</b> Vertex-Solutions MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILTY OR FITNESS FOR A PARTICULAR PURPOSE, WITH REGARD TO DELIVERIES OR WITH REGARD TO ITS WEBSITE, INFORMATION PROVIDED ON ITS WEBSITE OR SERVICES RELATED TO TRANSACTIONS CONDUCTED ON ITS WEBSITE. Vertex-Solutions CANNOT GUARANTEE DELIVERY BY ANY SPECIFIC TIME OR DATE. IN ANY EVENT, Vertex-Solutions SHALL NOT BE LIABLE FOR ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS OR INCOME, WHETHER OR NOT Vertex-Solutions HAD KNOWLEDGE THAT SUCH DAMAGES MIGHT BE INCURRED.
                            <br/>
                            <br/>
                            <b>21) Venue, Forum Selection and Choice of Law:</b> Customer acknowledges that Vertex-Solutions is a Freight Broker based in and operating within the State of Califoria. Except where pre-empted by applicable federal laws and regulations, this Agreement is governed by the laws of the State of Califoria, without regard to its choice of law doctrines. Vertex-Solutions, Customer and the selected Carrier (pursuant to its separate agreement with Vertex-Solutions) agree that the venue for any legal action relating to Services provided by Vertex-Solutions or its websites, shall be exclusively in the courts of Orange County, Califoria or in the United States District Court for the Central District of Califoria, Southern Division. In the event Vertex-Solutions is the prevailing party in any legal action to enforce these Terms and Conditions or to collect payment from Customer, Vertex-Solutions shall be entitled to recover its reasonable attorney fees and expenses from Customer.
                            <br/>
                            <br/>
                            <b>22) Payment for Services:</b> Customer accepts full responsibility for a correct and accurate BOL. Customer agrees to pay for all Services as actually provided. Billing will be based on the actuality of the following; Actual commodity shipped, actual shipping weight including packing, crating and pallet, actual dimensions, actual volume, NMFC commodity code, actual freight class, number of items, type of service requested and other applicable accessorial charges, including, but not limited to all duties, customs assessments, governmental penalties and fines, taxes, and Vertex-Solutions’s attorney fees and legal costs allocable to this Shipment and/or all disputes related to the Shipment.
                            <br/>
                            <br/>
                            <b>23) All Services are charged to Customer’s account at the time of dispatch for our prompt-pay discount rates.</b> If payment is not received for Services within Customer’s agreed-to terms of account, (a) a one-time reprocessing charge of $50 will be applied to the account and (b) late fees will be 10% of the total amount past due. All funds received by Vertex-Solutions will be applied to the oldest (based on pickup date) outstanding invoice.
                            <br/>
                            <br/>
                            <b>24) Should the actual Shipment’s description or the actually required Services prove to be different than shown on the BOL, additional charges will be assessed and charged to Customer’s account.</b> When paying by credit card or electronic funds, Customer agrees it will be responsible for all charges payable, including any adjustments, on account of such Customer’s shipment. These charges and adjustments, if any, will be automatically debited to Customer’s credit card or bank account.
                            <br/>
                            <br/>
                            <b>25) Because Vertex-Solutions is not the actual carrier, Customer agrees that it will not withhold payment or deny liability for payment to Vertex-Solutions for reasons related to disputes with the Carrier.</b>
                            <br/>
                            <br/>
                            <b>26) Method of Payment:</b> Unless Customer is registered under a plan offering a specialized payment method, Customer must provide a credit card account number which is issued in Customer’s name or which Customer is authorized to use when registering for the Services. This card will be used as Customer’s primary method of payment. All payments shall be made pursuant to the terms of the pricing and other information relating to the Services selected. By agreeing to these Terms and Conditions, Customer is authorizing and directing Vertex-Solutions to automatically charge any amounts payable by Customer in connection with Customer’s use of transportation services to the credit card Customer provided in the registration process or such credit card number Customer may provide thereafter. It is Customer’s responsibility to update the credit card information that Customer uses to pay for the services. If Customer bills its use of Vertex-Solutions’s Services to its credit card, Customer’s right to use the Services is subject to any limits established by Customer’s credit card issuer. If Customer does not update its credit card information, Vertex-Solutions may suspend Customer’s use of the Services or, at Vertex-Solutions’s option, may automatically move Customer onto another bill payment arrangement. Vertex-Solutions may also make other billing options available. If Vertex-Solutions makes other billing options available, Customer agrees to abide by terms and conditions applicable to those options.
                            <br/>
                            <br/>
                            <b>27) Changes in Terms and Conditions:</b> Vertex-Solutions shall have the right at any time to change or modify the terms and conditions applicable to Customer’s uses of Vertex-Solutions’s Services, or to impose new conditions, including, but not limited to, adding fees and charges for use. Such changes, modifications, additions or deletions shall be effective immediately upon notice thereof, which may be given by means including, but not limited to electronic or conventional mail, or by any other means by which Customer obtains notice thereof. Any use of Vertex-Solutions’s Services by Customer after such notice shall be deemed to constitute acceptance by Customer of such changes, modifications or additions.
                            <br/>
                            <br/>
                            <b>28) Severability:</b> In the event that any term, condition or provision of this Agreement is found by a court of competent jurisdiction to be invalid or unenforceable, the remainder of the Agreement shall be unaffected.
                            <br/>
                            <br/>
                            <b>29) No Waiver:</b> The failure of Vertex-Solutions to insist upon the prompt and punctual performance of any term or condition in this Agreement, or the failure of Vertex-Solutions to insist upon or exercise any right or remedy under this Agreement on any one or more occasions, shall not constitute a waiver of that or any other term, condition, right or remedy on that or any subsequent occasion.
                            <br/>
                            <br/>
                            <b>30) INDEMNIFICATION:</b> IN THE EVENT ANY LEGAL ACTION OR CLAIM IS MADE AGAINST Vertex-Solutions, OR ANY FINES OR PENALTIES ARE ASSESSED AGAINST Vertex-Solutions, ARISING OUT OF ANY ACT, OMISSION OR NEGLIGENCE OF CUSTOMER, CUSTOMER AGREES TO INDEMNIFY AND DEFEND Vertex-Solutions AGAINST ANY AND ALL SUCH CLAIMS, DEMANDS, LOSSES, COSTS, OBLIGATIONS, FINES, PENALTIES, AND LIABILITIES.
                            <br/>
                            <br/>
                            <b>31) Binding Effect:</b> The individual purchasing the services contemplated under these Terms and Conditions on behalf of Customer acknowledges and agrees that he/she has the express and actual authority to bind Customer to this Agreement. This Agreement will be binding upon and inure to the benefit of the Parties and their respective heirs, successors, and assigns.
                            <br/>
                            <br/>
                            <b>32) Interpretation:</b> These Terms and Conditions supersede all agreements, representations, warranties, statements, promises, and understandings of the parties, written or oral, except as stated herein. Where a Customer enters into a separate written and duly executed contractual agreement with Vertex-Solutions, only the conflicting terms in that agreement will take precedence over these Terms and Conditions. Any General Rules Tariffs set forth by a selected Carrier, will in every instance take precedence in all legal proceedings, and when in conflict, will take precedence over these Terms and Conditions.
                            </p>

                            


                        </div>
                    </div>
                </div>
            </div>
            <img className="background-image-left" src={colorSharp} alt="" />
        </section>
    )
}
